# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: pretty-format-json
    args: [--no-sort-keys, --autofix]
  - id: check-merge-conflict
      #- id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
    args: [--application-directories, .:src, --py36-plus]
#- repo: https://github.com/myint/docformatter
#  rev: v1.4
#  hooks:
#  - id: docformatter
#    args: [--in-place]
- repo: https://github.com/ambv/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3.10
    args: [--target-version, py310]
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
#        additional_dependencies: [radon]
#        args: ["--radon-max-cc=10", "--radon-show-closures"]  # wait for radon to support 3.10
